[package]
name = "utoipa-gen"
description = "Code generation implementation for utoipa"
version = "1.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["openapi", "codegen", "proc-macro", "documentation", "compile-time"]
repository = "https://github.com/juhaku/utoipa"
authors = [
  "Juha Kukkonen <juha7kukkonen@gmail.com>"
]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro-error = "1.0"
regex = { version = "1.5", optional = true } 
lazy_static = { version = "1.4", optional = true }
uuid = { version = "1", optional = true }
utoipa-corelib = { path = "../utoipa-corelib", version = "0.1" }
utoipa-gen-actix-web = { path = "../utoipa-gen-actix-web", version = "0.1", optional = true }
utoipa-gen-rocket = { path = "../utoipa-gen-rocket", version = "0.1", optional = true }
utoipa-gen-axum = { path = "../utoipa-gen-axum", version = "0.1", optional = true }

[dev-dependencies]
utoipa = { path = "..", default-features = false }
serde_json = "1"
serde = "1"
actix-web = { version = "4", features = [ "macros" ], default-features = false }
axum = "0.5"
paste = "1"
rocket = "0.5.0-rc.1"
smallvec = { version = "1.9.0", features = [ "serde" ] }
rust_decimal = "1"
chrono = { version  = "0.4", features = ["serde"] }
assert-json-diff = "2"
time = { version = "0.3.11", features = [ "serde-human-readable" ] }

[features]
debug = ["utoipa-corelib/debug", "utoipa-gen-actix-web?/debug", "utoipa-gen-rocket?/debug", "utoipa-gen-axum?/debug" ]
actix_extras = ["regex", "lazy_static", "syn/extra-traits", "utoipa-gen-actix-web" ]
rocket_extras = ["regex", "lazy_static", "syn/extra-traits", "utoipa-gen-rocket" ]
axum_extras = ["syn/extra-traits", "utoipa-gen-axum" ]
chrono = ["utoipa-corelib/chrono" ]
chrono_with_format = ["utoipa-corelib/chrono_with_format" ]
json = []
yaml = []
decimal = ["utoipa-corelib/decimal" ]
uuid = ["dep:uuid", "utoipa-corelib/uuid" ]
time = [ "utoipa-corelib/time" ]
smallvec = [ "utoipa-corelib/smallvec" ]
